Thermal Fine tuning for TGL NUC BM
projectceladon/device-intel-common pull request #113
Opened 2021-12-06 09:59 UTC by vilasrk

To avoid unexpected shutdown and mitigate
excessive thermal, fine tuning of thermal
parameters has been done

Tracked on:OAM-99878
Signed-off-by: vilasrk <vilas.r.k@intel.com>

2021-12-06 10:36 UTC, balajim001 approved these changes
LGTM

2021-12-07 04:26 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/131

2021-12-07 04:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/132

2021-12-07 04:36 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/133

2021-12-07 04:42 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/134

2021-12-07 05:12 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/135

2021-12-07 06:05 UTC, kaushlen approved these changes

2021-12-07 07:33 UTC, JeevakaPrabu requested changes
detailed information on value changes in commit message would be good

2021-12-07 10:03 UTC, JeevakaPrabu approved these changes

2021-12-07 11:24 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/136

Done by "R K, Vilas" <vilas.r.k@intel.com>

2021-12-07 14:48 UTC, shyjumon-n approved these changes
LGTM

2021-12-07 15:06 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-premerge/builds/105

Done by "R K, Vilas" <vilas.r.k@intel.com>

2021-12-07 22:10 UTC, merged

2021-12-07 22:11 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "R K, Vilas" <vilas.r.k@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_stable-mergerequest/builds/73