Enable provision to compile vm1-2 and vm3 separately
projectceladon/device-intel-common pull request #189
Opened 2023-11-29 10:26 UTC by sgnanase

2023-11-29 10:28 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2023-11-29 10:29 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-30 01:10 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-12-11 03:07 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 03:08 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 03:10 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 03:11 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 03:12 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 03:19 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 04:30 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 04:59 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 04:59 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 05:01 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 05:02 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 05:02 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 05:09 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 05:14 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 06:33 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-11 07:14 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 08:12 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-11 12:07 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-12 06:29 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 06:31 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 06:32 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 06:33 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-12 06:34 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-12 06:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 06:37 UTC, swaroopbalan approved these changes

2023-12-12 06:38 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 06:41 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-12 07:17 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 07:19 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-12 07:23 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-12-12 07:25 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-12 18:46 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-12-13 15:43 UTC, JeevakaPrabu requested changes
- Tests done missing
- adding edid folder and deleting few files under edid and firmware folder. Need detailed message of why this is being done

2024-01-10 02:22 UTC, bing8deng approved these changes

2024-01-10 04:26 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1409

2024-01-10 07:02 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1410

Done by "Gnanasekaran, Sundar" <sundar.gnanasekaran@intel.com>

2024-01-10 07:04 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/753

Done by "Gnanasekaran, Sundar" <sundar.gnanasekaran@intel.com>

2024-01-10 09:03 UTC, merged

2024-01-10 09:04 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Gnanasekaran, Sundar" <sundar.gnanasekaran@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/773