Disable support for vendor specific extensions
projectceladon/device-intel-common pull request #94
Opened 2021-02-11 09:10 UTC by aiswaryacyriac

support for vendor specific extensions such as RPA offloading,
feature discovery, multi-adv etc

Tracked-On: OAM-95807
Signed-off-by: Aiswarya Cyriac <aiswarya.cyriac@intel.com>

2021-02-12 12:01 UTC, balajim001 approved these changes
LGTM

2021-02-13 05:29 UTC, JeevakaPrabu requested changes
Disable word missing in commit message "support for vendor specific extensions such as RPA offloading, feature discovery, multi-adv etc"

2021-02-13 06:42 UTC, balajim001 approved these changes
LGTM

2021-02-13 06:45 UTC, JeevakaPrabu approved these changes

2021-02-13 12:01 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3009

Done by "Cyriac, Aiswarya" <aiswarya.cyriac@intel.com>

2021-02-13 12:48 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug), CIT-CIV-CML-R(cml_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1517

2021-02-15 06:55 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests cancelled

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1518

2021-02-15 08:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1519

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2021-02-15 11:16 UTC, merged

2021-02-15 11:16 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2238